export enum UserRole {
  ADMIN = 'ROLE_ADMIN',
  CLIENT = 'ROLE_CLIENT',
  INSTRUCTOR = 'ROLE_INSTRUCTOR',
  LODGE_OWNER = 'ROLE_LODGE_OWNER',
  UNDEFINED = 'ROLE_UNDEFINED',
  SHIP_OWNER = 'ROLE_SHIP_OWNER',
}
